### ISSUE TITLE
ModuleNotFoundError: No module named 'pywintypes'

### ISSUE THREAD

**Issue by futag** [Kalmat/PyMonCtl#8]
I'm using embedded python 3.10.11.

Log Error:
```
Traceback (most recent call last):
  File "F:\OBS-Studio-29.1.3\assets\python3.10\zoom_and_follow_mouse.py", line 6, in <module>
    import pywinctl as pwc
  File "F:\OBS-Studio-29.1.3\assets\python3.10\Lib\site-packages\pywinctl\__init__.py", line 27, in <module>
    from ._main import (Re, Window, checkPermissions, getActiveWindow,
  File "F:\OBS-Studio-29.1.3\assets\python3.10\Lib\site-packages\pywinctl\_main.py", line 14, in <module>
    from pymonctl import findMonitorsAtPoint, getAllMonitors, getAllMonitorsDict
  File "F:\OBS-Studio-29.1.3\assets\python3.10\Lib\site-packages\pymonctl\__init__.py", line 22, in <module>
    from ._main import (getAllMonitors, getAllMonitorsDict, getMonitorsCount, getPrimary,
  File "F:\OBS-Studio-29.1.3\assets\python3.10\Lib\site-packages\pymonctl\_main.py", line 912, in <module>
    from ._pymonctl_win import (_getAllMonitors, _getAllMonitorsDict, _getMonitorsCount, _getPrimary,
  File "F:\OBS-Studio-29.1.3\assets\python3.10\Lib\site-packages\pymonctl\_pymonctl_win.py", line 12, in <module>
    import pywintypes
ModuleNotFoundError: No module named 'pywintypes'
```

**Comment by futag** [comment]
Nevermind https://github.com/mhammond/pywin32/issues/1618#issuecomment-968633499
