### ISSUE TITLE
Py 3.7 Syntax Error on 0.7

### ISSUE THREAD

**Issue by cman122887** [Kalmat/PyMonCtl#9]
```>>> import pymonctl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/virtualenv/pymonctl/lib/python3.7/site-packages/pymonctl/__init__.py", line 22, in <module>
    from ._main import (getAllMonitors, getAllMonitorsDict, getMonitorsCount, getPrimary,
  File "/Users/me/virtualenv/pymonctl/lib/python3.7/site-packages/pymonctl/_main.py", line 643
    _updateScreens: Optional[_UpdateScreens] = None
    ^
SyntaxError: annotated name '_updateScreens' can't be global
```

which seems to have been fixed in 3.8?
https://github.com/python/cpython/commit/de2aea0ff02fa9486365ce9d215bef150fae3a0b

If you are able to repro on your end it might be worth considering removal of the 3.7 classifier

**Comment by Kalmat** [comment]
Hi! First off, sorry for my late reply. I've been very busy these last months, so I completely missed your issue. Secondly, thanks a lot for your help!

I will remove 3.7 classifier in next version. Thank you again!
